spring:
  application:
    name: base

  #指定数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource


  #redis配置
  redis:
    password:

server:
  port: 7013


eureka:
  instance:
    #心跳超时时间10s，默认90s。从client端最后一次发出心跳后，达到这个时间没有再次发出心跳，表示服务不可用，将它的实例从注册中心移除
    lease-expiration-duration-in-seconds: 1
    #心跳间隔5s，默认30s。每一个服务配置后，心跳间隔和心跳超时时间会被保存在server端，不同服务的心跳频率可能不同，server端会根据保存的配置来分别探活
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://peer1-eureka:7001/eureka/,http://peer1-eureka:7002/eureka/


datasource1:
  jdbcUrl: jdbc:mysql://localhost:3306/mydb?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=GMT
  username: root
  password:
  driverClassName: com.mysql.cj.jdbc.Driver

datasource2:
  jdbcUrl: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=GMT
  username: root
  password:
  driverClassName: com.mysql.cj.jdbc.Driver

task:
  pool:
    corePoolSize: 5
    maxPoolSize: 10
    keepAliveSecondes: 60
    queueCapacity: 1000
    threadNamePrefix: luxin-

logging:
  level:
    root: INFO
    com.luxin.base: INFO
